# Generated by Django 2.1.3 on 2018-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tytuł')),
                ('message', models.TextField(verbose_name='Treść wiadomości')),
                ('recipient', models.CharField(max_length=500, verbose_name='Nadawca')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.PositiveIntegerField()),
                ('errors', models.PositiveIntegerField()),
            ],
        ),
    ]
