# Generated by Django 2.1.3 on 2018-11-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.CharField(max_length=500, verbose_name='Adresat'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='success',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
