# Generated by Django 2.1.3 on 2018-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_auto_20181112_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sended',
            field=models.BooleanField(default=None, verbose_name='Wysłane'),
            preserve_default=False,
        ),
    ]
