# Generated by Django 2.1.3 on 2018-11-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_email_sended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sended',
            field=models.BooleanField(default=False, verbose_name='Wysłane'),
        ),
    ]
